CREATE TABLE role_permission_sets(
  role text PRIMARY KEY CHECK(role IN ('SALES_REP','SALES_MANAGER','WAREHOUSE_MANAGER','FINANCE','LOGISTICS','DRIVER','SUPER_ADMIN')),
  permissions text[] NOT NULL DEFAULT '{}',
  version integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT role_permission_values CHECK(
    permissions <@ ARRAY[
      'ORDERS_VIEW','ORDERS_CREATE','FINANCE_RECOMMEND','MANAGER_DECIDE',
      'WAREHOUSE_PREPARE','LOGISTICS_VIEW','DELIVERY_CONFIRM','INVENTORY_VIEW',
      'INVENTORY_RECEIVE','RECEIPTS_APPROVE','CUSTOMERS_MANAGE','PRODUCTS_MANAGE',
      'STOCK_ADJUST','USERS_MANAGE','AREAS_MANAGE','ACTIVITY_VIEW'
    ]::text[]
  )
);

INSERT INTO role_permission_sets(role,permissions) VALUES
  ('SALES_REP',ARRAY['ORDERS_VIEW','ORDERS_CREATE']),
  ('SALES_MANAGER',ARRAY['ORDERS_VIEW','MANAGER_DECIDE','INVENTORY_VIEW']),
  ('WAREHOUSE_MANAGER',ARRAY['ORDERS_VIEW','WAREHOUSE_PREPARE','INVENTORY_VIEW','INVENTORY_RECEIVE']),
  ('FINANCE',ARRAY['ORDERS_VIEW','FINANCE_RECOMMEND','INVENTORY_VIEW','RECEIPTS_APPROVE','CUSTOMERS_MANAGE','PRODUCTS_MANAGE']),
  ('LOGISTICS',ARRAY['ORDERS_VIEW','LOGISTICS_VIEW']),
  ('DRIVER',ARRAY['ORDERS_VIEW','DELIVERY_CONFIRM']),
  ('SUPER_ADMIN',ARRAY[
    'ORDERS_VIEW','ORDERS_CREATE','FINANCE_RECOMMEND','MANAGER_DECIDE',
    'WAREHOUSE_PREPARE','LOGISTICS_VIEW','DELIVERY_CONFIRM','INVENTORY_VIEW',
    'INVENTORY_RECEIVE','RECEIPTS_APPROVE','CUSTOMERS_MANAGE','PRODUCTS_MANAGE',
    'STOCK_ADJUST','USERS_MANAGE','AREAS_MANAGE','ACTIVITY_VIEW'
  ]);
